var myChart = echarts.init(document.getElementById('main'));  
        option = { backgroundColor: '#404a59', 
            title: {      
                text: '全球2019年GDP', 
                left: 'center',  
                top: 'top'  ,
                textStyle: {
                    color: '#fff'
                }
            },  
            toolbox: {
                show: true,            
                left: '90%',
                top: 'top',
                feature: {
                  mark: { show: true },
                  dataView: { show: true, readOnly: false },
                  saveAsImage: { show: true }
                }
                
              },
           tooltip: {  
                trigger: 'item',  
                formatter: function (params) {  
                    var value = (params.value + '').split('.');  
                    value = value[0].replace(/(\d{1,3})(?=(?:\d{3})+(?!\d))/g, '$1,')  
                            + '.' + value[1];  
                    return params.seriesName + '<br/>' + params.name + ' : ' +'$'+ value + '万亿';  
                }  
            },      
            visualMap: {  
                min: 0,  
                max: 22,  
                text:['High','Low'],  
                realtime: false,  
                calculable: true,  
                color: ['orangered','yellow','lightskyblue'],
                textStyle: {
                    color: '#fff'
                }
            },  
            series: [  
                {  
                    name: 'GDP(2019)',  
                    type: 'map',  
                    mapType: 'world',  
                    roam: true,  
                    itemStyle:{  
                        emphasis:{label:{show:true}}  
                    },  
                    data: [  
                        {name:'United States', value:21.34	},
                        {name:'China', value:14.22},
                        {name:'Japan', value:5.18},
                        {name:'Germany', value:3.96},
                        {name:'India', value:2.97},
                        {name:'United Kingdom',value:2.83},
                        {name:'France', value:2.76},
                        {name:'Italy', value:2.03},
                        {name:'Brazil', value:1.96},
                        {name:'Canada', value:1.74},
                        {name:'South Korea', value:1.66},
                        {name:'Russia', value:1.61},
                        {name:'Spain', value:1.43},
                        {name:'Australia', value:1.42},
                        {name:'Mexico', value:1.24},
                        {name:'Indonesia', value:1.1},
                        {name:'Netherlands', value:0.914},
                        {name:'Saudi Arabia', value:0.76226},
                        {name:'Switzerland', value:0.70757},
                        {name:'Turkey', value:0.70624},
                        {name:'Taiwan, China', value:0.60143},
                        {name:'Poland', value:0.59329},
                        {name:'Sweden'	, value:0.54712},
                        {name:'Belgium', value:0.53181	},
                        {name:'Thailand', value:0.51666},
                        {name:'Iran', value:0.48466	},
                        {name:'Argentina', value:0.47774	},
                        {name:'Austria', value:0.45959	},
                        {name:'Nigeria', value:0.44492	},
                        {name:'United Arab Emirates', value:0.42788},
                        {name:'Norway', value:0.42704	},
                        {name:'China Hong Kong', value:3.8172	},
                        {name:'Ireland', value:0.38157	},
                        {name:'Israel', value:	0.38157	},
                        {name:'Malaysia', value:0.37345	},
                        {name:'Singapore', value:0.37281	},
                        {name:'South Africa', value:0.3713	},
                        {name:'Philippines', value:0.35668	},
                        {name:'Denmark', value:0.34952	},
                        {name:'Colombia', value:0.3366	},
                        {name:'Bangladesh', value:0.31466	},
                        {name:'Egypt', value:0.29959	},
                        {name:'Chile', value:0.29561	},
                        {name:'Pakistan', value:0.27802	},
                        {name:'Finland', value:0.27657	},
                        {name:'Vietnam', value:0.2603	},
                        {name:'Czech Republic', value:0.24616	},
                        {name:'Romania', value:0.24416	},
                        {name:'Portugal' , value:0.23947	},
                        {name:'Peru' , value:0.23208	},
                        {name:'Iraq'	 , value:0.22526	},
                        {name:'Greece'	 , value:0.21975	},
                        {name:'new Zealand'	 , value:0.21047	},
                        {name:'Qatar'	 , value:0.1935	},
                        {name:'Algeria'	 , value:0.18369	},
                        {name:'Hungary'	 , value:0.16878	},
                        {name:'Kazakhstan'	 , value:0.16421	},
                        {name:'Kuwait'	 , value:0.13694	},
                        {name:'Ukraine'	 , value:0.13489	},
                        {name:'Morocco'	 , value:0.12135	},
                        {name:'Slovakia'	 , value:0.10986	},
                        {name:'Ecuador'	 , value:0.10629	},
                        {name:'Puerto Rico'	 , value:0.10351	},
                        {name:'Kenya'	 , value:0.09925	},
                        {name:'Angola'	 , value:0.09219	},
                        {name:'Ethiopia'	 , value:0.09097	},
                        {name:'Dominican Republic'	 , value:0.08484	},
                        {name:'Sri Lanka'	 , value:0.08416	},
                        {name:'Guatemala'	 , value:0.08233	},
                        {name:'Oman'	 , value:0.07946	},
                        {name:'Venezuela'	 , value:0.07646	},
                        {name:'Panama'	 , value:0.07016	},
                        {name:'Luxembourg'	 , value:0.06963	},
                        {name:'Ghana'	 , value:0.06826	},
                        {name:'Bulgaria'	 , value:0.06704	},
                        {name:'Myanmar'	 , value:0.06567	},
                        {name:'Croatia'	 , value:0.06125	},
                        {name:'Tanzania'	 , value:0.06103	},
                        {name:'Belarus'	 , value:0.06095	},
                        {name:'Costa Rica'	 , value:0.06046	},
                        {name:'Uruguay'	 , value:0.06023	},
                        {name:'Lebanon'	 , value:0.05828	},
                        {name:'Macao, China'	 , value:0.05805	},
                        {name:'Slovenia'	 , value:0.05509	},
                        {name:'Lithuania'	 , value:0.05424	},
                        {name:'Turkmenistan'	 , value:0.05035	},
                        {name:'Uzbekistan'	 , value:0.0492	},
                        {name:'Democratic Republic of Congo'	 , value:0.04846	},
                        {name:'Ivory coast'	 , value:0.04525	},
                        {name:'Azerbaijan'	 , value:0.04525	},
                        {name:'Libya'	 , value:0.04496	},
                        {name:'Jordan'	 , value:0.04426	},
                        {name:'Bolivia'	 , value:0.04369	},
                        {name:'Paraguay'	 , value:0.04235	},
                        {name:'Cameroon'	 , value:0.03922	},
                        {name:'Bahrain'	 , value:0.03895	},
                        {name:'Tunisia'	 , value:0.0362	},
                        {name:'Latvia'	 , value:0.03572	},
                        {name:'Estonia'	 , value:0.03103	},
                        {name:'Uganda'	 , value:0.03037	},
                        {name:'Yemen'	 , value:0.02908	},
                        {name:'Nepal'	 , value:0.02892	},
                        {name:'Salvador'	 , value:0.02699	},
                        {name:'Cambodia'	 , value:0.02698	},
                        {name:'Senegal'	 , value:0.02532	},
                        {name:'Honduras'	 , value:0.02465	},
                        {name:'Cyprus'	 , value:0.02464	},
                        {name:'Zambia'	 , value:0.02461	},
                        {name:'Iceland'	 , value:0.02454	},
                        {name:'Trinidad and Tobago'	 , value:0.02244	},
                        {name:'Zimbabwe'	 , value:0.02229	},
                        {name:'Papua New Guinea'	 , value:0.02145	},
                        {name:'Laos'	 , value:0.02015	},
                        {name:'Bosnia and Herzegovina'	 , value:	0.02015	},
                        {name:'Afghanistan'	 , value:	0.01999	},
                        {name:'Botswana'	 , value:	0.01965	},
                        {name:'Mali'	 , value:0.01783	},
                        {name:'Georgia'	 , value:0.01721	},
                        {name:'Gabon'	 , value:0.01671	},
                        {name:'Jamaica'	 , value:0.01615	},
                        {name:'Albania'	 , value:0.01596	},
                        {name:'Mozambique'	 , value:0.01537	},
                        {name:'Malta'	 , value:0.01513	},
                        {name:'Burkina Faso'	 , value:0.01488	},
                        {name:'Mauritius'	 , value:0.01481	},
                        {name:'Namibia'	 , value:0.01396	},
                        {name:'Mongolia'	 , value:0.0137	},
                        {name:'Brunei'	 , value:0.01332	},
                        {name:'Bahamas'	 , value:0.01326	},
                        {name:'Armenia'	 , value:0.01311	},
                        {name:'Macedonia'	 , value:0.01288	},
                        {name:'Madagascar'	 , value:0.01273	},
                        {name:'Guinea'	 , value:0.01262	},
                        {name:'Nicaragua'	 , value:0.01261	},
                        {name:'Equatorial Guinea'	 , value:0.01243	},
                        {name:'Moldova'	 , value:	0.01204	},
                        {name:'Chad'	 , value:	0.01137	},
                        {name:'Benin'	 , value:	0.01118	},
                        {name:'the republic of Congo'	 , value:0.01116	},
                        {name:'Rwanda'	 , value:0.01021	},
                        {name:'Niger'	 , value:0.00972	},
                        {name:'Haiti'	 , value:0.0096	},
                        {name:'Kyrgyzstan'	 , value:0.00833	},
                        {name:'Somalia'	 , value:0.0079	},
                        {name:'Eritrea'	 , value:0.00772	},
                        {name:'Tajikistan'	 , value:0.0077	},
                        {name:'Malawi'	 , value:0.00744	},
                        {name:'Maldives'	 , value:0.00575	},
                        {name:'Togo'	 , value:0.00559	},
                        {name:'Mauritania'	 , value:0.00557	},
                        {name:'Montenegro'	 , value:0.00544	},
                        {name:'Fiji'	 , value:0.00532	},
                        {name:'Barbados'	 , value:0.00521	},
                        {name:'Swaziland'	 , value:0.00466	},
                        {name:'Sierra Leone'	 , value:0.004	},
                        {name:'Guyana'	 , value:0.00383	},
                        {name:'Suriname'	 , value:0.00368	},
                        {name:'Burundi'	 , value:0.00357	},
                        {name:'Liberia'	 , value:0.00322	},
                        {name:'South Sudan'	 , value:0.00315	},
                        {name:'East Timor'	 , value:0.00315	},
                        {name:'Aruba'	 , value:0.00288	},
                        {name:'Bhutan'	 , value:0.00284	},
                        {name:'Lesotho'	 , value:0.00281	},
                        {name:'Djibouti'	 , value:0.00239	},
                        {name:'Central African Republic'	 , value:0.00229	},
                        {name:'Cape Verde'	 , value:0.00204	},
                        {name:'Saint Lucia'	 , value:0.002	},
                        {name:'Gambia'	 , value:0.00197	},
                        {name:'Antigua and Barbuda'	 , value:0.00174	},
                        {name:'Seychelles', value:0.00172	},
                        {name:'San Marino', value:0.00165	},
                        {name:'Guinea-Bissau', value:0.00162	},
                        {name:'Solomon Islands', value:0.00154	},
                        {name:'Grenada'	 , value:0.00151	},
                        {name:'Saint Kitts and Nevis'	 , value:0.00127	},
                        {name:'Vanuatu'	 , value:	0.00106	},
                        {name:'Saint Vincent and the Grenadines'	 , value:0.0009002	},
                        {name:'Comoros'	 , value:0.000864	},
                        {name:'Tonga'	 , value:0.000542	},
                        {name:'Sao Tome and Principe'	 , value:0.000493	},
                        {name:'Micronesia'	 , value:0.000477	},
                        {name:'ulu'	 , value:0.000383	},
                        {name:'Marshall Islands' , value:0.00031	},
                        {name:'Kiribati'	 , value:0.00022	},
                        {name:'Nauru'	 , value:0.000187	},
                        {name:'Tuvalu'	 , value:0.000114	},
                        {name:'Andorra'	 , value:0.000049	}                   
                    ] 
                }  
            ]  
        };  
        myChart.setOption(option);